POST http://localhost:8005/api/v1/run HTTP/1.1
content-type: application/json

{
    "language": "cpp",
    "code": "#include<iostream> #include<string> int main() {string name = "";getline (std::cin, name);std::cout<<\"Hello \"<<name;return 0;}",
    "inputs": "Anish"
}