POST http://localhost:8000/api/v1/users/register HTTP/1.1
content-type: application/json

{
    "username": "lookb4uleap",
    "email": "anish.sarkar.official@gmail.com",
    "password": "1234567890"
}
###
POST http://localhost:8000/api/v1/users/login HTTP/1.1
content-type: application/json

{
    "username": "lookb4uleap",
    "password": "1234567890"
}
### 
POST http://localhost:8000/api/v1/problems HTTP/1.1
content-type: application/json

{
    "problemTitle": "Sum of N numbers",
    "problemDescription": "Given a sequence of N numbers output the sum of all the numbers in the sequence.",
    "inputDescription": "First line is a number N (1<=N<=10^5) denoting the sequence lenght. Next line contains N space separated numbers a[i] (-10^4 <= a[i] <= 10^4) belonging to this sequence",
    "outputDescription": "Display a single number which will be the sum of the sequence",
    "points": 5
}
###
GET http://localhost:8000/api/v1/problems HTTP/1.1
###
GET http://localhost:8000/api/v1/problems/66ca439ffa39af2a028eb050 HTTP/1.1
###
POST http://localhost:8000/api/v1/testcases HTTP/1.1
Content-Type: application/json

{
    "problemId": "66ca439ffa39af2a028eb050",
    "type": "sample",
    "input": "https://codolympics-testcase-outputs.s3.ap-south-1.amazonaws.com/cc19a115-5a45-4168-8562-aa8256497b83.txt",
    "output": "https://codolympics-testcase-outputs.s3.ap-south-1.amazonaws.com/6cf80232-20a9-4b7d-9845-202ad5b9843a.txt",
    "points": 5
}
###
GET http://localhost:8000/api/v1/testcases/upload HTTP/1.1
Authorization:
###
POST http://localhost:8000/api/v1/problems HTTP/1.1
Content-Type: application/json
Authorization:

{
    
}
